const Tag = Object.freeze({
  ARRAY: 'Array',
  STRING: 'String',
  HASH_TABLE: 'Hash Table',
  DYNAMIC_PROGRAMMING: 'Dynamic Programming',
  MATH: 'Math',
  SORTING: 'Sorting',
  GREEDY: 'Greedy',
  DFS: 'Depth-First Search',
  DATABASE: 'Database',
  BINARY_SEARCH: 'Binary Search',
  BFS: 'Breadth-First Search',
  TREE: 'Tree',
  MATRIX: 'Matrix',
  TWO_POINTERS: 'Two Pointers',
  BIT_MANIPULATION: 'Bit Manipulation',
  BINARY_TREE: 'Binary Tree',
  HEAP: 'Heap (Priority Queue)',
  STACK: 'Stack',
  PREFIX_SUM: 'Prefix Sum',
  GRAPH: 'Graph',
  SIMULATION: 'Simulation',
  DESIGN: 'Design',
  COUNTING: 'Counting',
  SLIDING_WINDOW: 'Sliding Window',
  BACKTRACKING: 'Backtracking',
  UNION_FIND: 'Union Find',
  LINKED_LIST: 'Linked List',
  ORDERED_SET: 'Ordered Set',
  MONOTONIC_STACK: 'Monotonic Stack',
  ENUMERATION: 'Enumeration',
  DIVIDE_AND_CONQUER: 'Divide and Conquer',
  TRIE: 'Trie',
  BITMASK: 'Bitmask',
  QUEUE: 'Queue',
  GEOMETRY: 'Geometry',
  SEGMENT_TREE: 'Segment Tree',
  TOPOLOGICAL_SORT: 'Topological Sort',
  BINARY_INDEXED_TREE: 'Binary Indexed Tree',
  HASH_FUNCTION: 'Hash Function',
  STRING_MATCHING: 'String Matching',
  SHORTEST_PATH: 'Shortest Path',
  COMBINATORICS: 'Combinatorics',
  RANDOMIZED: 'Randomized',
  MINIMUM_SPANNING_TREE: 'Minimum Spanning Tree',
  GAME_THEORY: 'Game Theory',
  BICONNECTED_COMPONENT: 'Biconnected Component',
  STRONGLY_CONNECTED_COMPONENT: 'Strongly Connected Component'
});

export const getAllTags = () => Object.values(Tag);

export default Tag;
